language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database job_board2_test' -U postgres
before_install:
  - gem update --system
  - gem --version
bundler_args: --binstubs=./bundler_stubs
notifications:
  recipients:
    - klebershimabuku@gmail.com
    - marcelomogami@gmail.com