language: ruby
rvm:
  - 1.9.2
  - 1.9.3
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test rake db:test:prepare --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database job_board2_test' -U postgres
bundler_args: --binstubs=./bundler_stubs
notifications:
  recipients:
    - klebershimabuku@gmail.com
    - marcelomogami@gmail.com